POST http://localhost:3001/users/create
Content-Type: application/json

{
    "firstName": "bhavya",
    "lastName": "surati",
    "email": "bhavyamsurati@gmail.com",
    "password": "SecurePass!123"
}
